/*
CREATED: 10/12/2020
MODIFIED: 22/12/2020
MODEL: LOGIC_BD2
DATABASE: POSTGRESQL 12
*/

-- CREATE TABLES SECTION -------------------------------------------------

-- TABLE PAYMENT_STATUS

CREATE TABLE "PAYMENT_STATUS"
(
  "ID" INTEGER NOT NULL,
  "STATUS" CHARACTER VARYING(50) NOT NULL
)
WITH (
  AUTOVACUUM_ENABLED=TRUE)
TABLESPACE "PAYMENT_STATUS"
;

ALTER TABLE "PAYMENT_STATUS" ADD CONSTRAINT "ID_PAYMENT_STATUS" PRIMARY KEY ("ID")
;

-- TABLE PAYMENT

CREATE TABLE "PAYMENT"
(
  "ID" INTEGER NOT NULL,
  "VALUE" MONEY NOT NULL,
  "DUE_DATE" DATE NOT NULL,
  "PAYMENT_STATUS_ID" INTEGER NOT NULL
)
WITH (
  AUTOVACUUM_ENABLED=TRUE)
;

CREATE INDEX "IX_REL_PAYMENT_STATUS" ON "PAYMENT" ("PAYMENT_STATUS_ID")
;

ALTER TABLE "PAYMENT" ADD CONSTRAINT "ID_PAYMENT" PRIMARY KEY ("ID")
;

-- TABLE CAR_STATUS

CREATE TABLE "CAR_STATUS"
(
  "ID" SERIAL,
  "STATUS" CHARACTER VARYING(100) NOT NULL,
  "START_DATE" DATE NOT NULL,
  "END_DATE" DATE,
  "DESCRIPTION" TEXT,
  "CAR_ID" CHARACTER VARYING(20)
)
WITH (
  AUTOVACUUM_ENABLED=TRUE)
;

CREATE INDEX "IX_REL_CAR_STATUS" ON "CAR_STATUS" ("CAR_ID")
;

ALTER TABLE "CAR_STATUS" ADD CONSTRAINT "ID_CAR_STATUS" PRIMARY KEY ("ID")
;

-- TABLE CAR

CREATE TABLE "CAR"
(
  "ID" CHARACTER VARYING(20) NOT NULL,
  "PRODUCTION_YEAR" DATE NOT NULL,
  "NUMBER_PLATE" CHARACTER VARYING(20) NOT NULL,
  "CAR_MODEL_ID" CHARACTER VARYING(100),
  "RESERVATION_ID" INTEGER,
  "RENTAL_ID" INTEGER
)
WITH (
  AUTOVACUUM_ENABLED=TRUE)
;

CREATE INDEX "IX_REL_CAR_RENTAL" ON "CAR" ("RENTAL_ID")
;

CREATE INDEX "IX_REL_CAR_MODEL" ON "CAR" ("CAR_MODEL_ID")
;

ALTER TABLE "CAR" ADD CONSTRAINT "ID_CAR" PRIMARY KEY ("ID")
;

-- TABLE CAR_CLASS

CREATE TABLE "CAR_CLASS"
(
  "ID" SERIAL,
  "CLASS" CHARACTER VARYING(50) NOT NULL,
  "PRICE" MONEY NOT NULL,
  "DESCRIPTION" TEXT,
  "DISCOUNT_ID" INTEGER,
  "RESERVATION_ID" INTEGER
)
WITH (
  AUTOVACUUM_ENABLED=TRUE)
;

CREATE INDEX "IX_REL_DISCOUNT" ON "CAR_CLASS" ("DISCOUNT_ID")
;

CREATE INDEX "IX_REL_RESERVATION" ON "CAR_CLASS" ("RESERVATION_ID")
;

ALTER TABLE "CAR_CLASS" ADD CONSTRAINT "ID_CAR_CLASS" PRIMARY KEY ("ID")
;

-- TABLE CAR_MODEL

CREATE TABLE "CAR_MODEL"
(
  "ID" CHARACTER VARYING(100) NOT NULL,
  "TRANSMISSION" CHARACTER VARYING(10),
  "LENGTH" INTEGER,
  "WIDTH" INTEGER,
  "HEIGHT" INTEGER,
  "WEIGHT" INTEGER,
  "DOORS" INTEGER,
  "CAR_CLASS_ID" INTEGER,
  "CAR_BRAND_ID" CHARACTER VARYING(100),
  "ENGINE_TYPE_ID" INTEGER
)
WITH (
  AUTOVACUUM_ENABLED=TRUE)
;

CREATE INDEX "IX_REL_CAR_CLASS" ON "CAR_MODEL" ("CAR_CLASS_ID")
;

CREATE INDEX "IX_REL_CAR_BRAND" ON "CAR_MODEL" ("CAR_BRAND_ID")
;

CREATE INDEX "IX_REL_ENGINE_TYPE" ON "CAR_MODEL" ("ENGINE_TYPE_ID")
;

ALTER TABLE "CAR_MODEL" ADD CONSTRAINT "ID_CAR_MODEL" PRIMARY KEY ("ID")
;

-- TABLE CAR_BRAND

CREATE TABLE "CAR_BRAND"
(
  "ID" CHARACTER VARYING(100) NOT NULL,
  "LOGO_URL" CHARACTER VARYING(100) NOT NULL,
  "DESCRIPTION" TEXT
)
WITH (
  AUTOVACUUM_ENABLED=TRUE)
;

ALTER TABLE "CAR_BRAND" ADD CONSTRAINT "ID_CAR_BRAND" PRIMARY KEY ("ID")
;

-- TABLE DISCOUNT

CREATE TABLE "DISCOUNT"
(
  "ID" INTEGER NOT NULL,
  "FACTOR" NUMERIC(8,2) NOT NULL,
  "START_DATE" DATE NOT NULL,
  "END_DATE" DATE
)
WITH (
  AUTOVACUUM_ENABLED=TRUE)
;

ALTER TABLE "DISCOUNT" ADD CONSTRAINT "ID_DISCOUNT" PRIMARY KEY ("ID")
;

-- TABLE ENGINE_TYPE

CREATE TABLE "ENGINE_TYPE"
(
  "ID" INTEGER NOT NULL,
  "NAME" CHARACTER VARYING(30) NOT NULL,
  "FAMILY" CHARACTER VARYING(40),
  "POWER" NUMERIC(6,0),
  "TORQUE" NUMERIC(8,2),
  "NOTES" TEXT,
  "ACCELERATION_TIME" NUMERIC(4,1)
)
WITH (
  AUTOVACUUM_ENABLED=TRUE)
;

ALTER TABLE "ENGINE_TYPE" ADD CONSTRAINT "ID_ENGINE_TYPE" PRIMARY KEY ("ID")
;

-- TABLE RESERVATION_STATUS

CREATE TABLE "RESERVATION_STATUS"
(
  "ID" INTEGER NOT NULL,
  "STATUS" CHARACTER VARYING(50) NOT NULL,
  "RESERVATION_ID" INTEGER
)
WITH (
  AUTOVACUUM_ENABLED=TRUE)
;

CREATE INDEX "IX_REL_RESERVATION_STATUS" ON "RESERVATION_STATUS" ("RESERVATION_ID")
;

ALTER TABLE "RESERVATION_STATUS" ADD CONSTRAINT "ID_RESERVATION_STATUS" PRIMARY KEY ("ID")
;

-- TABLE RENTAL

CREATE TABLE "RENTAL"
(
  "ID" SERIAL,
  "CREATED_AT" TIMESTAMP NOT NULL,
  "START_DATE" TIMESTAMP NOT NULL,
  "END_DATE" TIMESTAMP NOT NULL,
  "PRICE" MONEY NOT NULL,
  "ODOMETER_START" INTEGER,
  "ODOMETER_STOP" INTEGER,
  "RETURN_DATE" DATE,
  "PAYMENT_ID" INTEGER,
  "EMPLOYEE_ID" CHARACTER VARYING(100),
  "CUSTOMER_ID" CHARACTER VARYING(100)
)
WITH (
  AUTOVACUUM_ENABLED=TRUE)
;

CREATE INDEX "IX_REL_PAYMENT" ON "RENTAL" ("PAYMENT_ID")
;

CREATE INDEX "IX_REL_RENTAL_EMPLOYEE" ON "RENTAL" ("EMPLOYEE_ID")
;

CREATE INDEX "IX_REL_RENTAL_CUSTOMER" ON "RENTAL" ("CUSTOMER_ID")
;

ALTER TABLE "RENTAL" ADD CONSTRAINT "UNIQUE_IDENTIFIER2" PRIMARY KEY ("ID")
;

-- TABLE RESERVATION

CREATE TABLE "RESERVATION"
(
  "ID" SERIAL NOT NULL,
  "CREATED_AT" TIMESTAMP NOT NULL,
  "START_DATE" TIMESTAMP NOT NULL,
  "END_DATE" TIMESTAMP NOT NULL,
  "PRICE" MONEY NOT NULL,
  "EXPIRES" DATE NOT NULL,
  "CUSTOMER_ID" CHARACTER VARYING(100)
)
WITH (
  AUTOVACUUM_ENABLED=TRUE)
;

CREATE INDEX "IX_REL_RESERV_CUSTOMER" ON "RESERVATION" ("CUSTOMER_ID")
;

ALTER TABLE "RESERVATION" ADD CONSTRAINT "UNIQUE_IDENTIFIER3" PRIMARY KEY ("ID")
;

-- TABLE EMPLOYEE

CREATE TABLE "EMPLOYEE"
(
  "ID" CHARACTER VARYING(100) NOT NULL,
  "PASSWORD" CHARACTER VARYING(100) NOT NULL,
  "FIRST_NAME" CHARACTER VARYING(30) NOT NULL,
  "LAST_NAME" CHARACTER VARYING(50) NOT NULL,
  "PESEL" CHARACTER VARYING(15),
  "IS_ACTIVE" BOOLEAN,
  "SALARY" MONEY NOT NULL,
  "ACCOUNT_NO" CHARACTER VARYING(30) NOT NULL,
  "ADDRESS_ID" INTEGER NOT NULL
)
WITH (
  AUTOVACUUM_ENABLED=TRUE)
;

CREATE INDEX "IX_REL_ADDRESS_1" ON "EMPLOYEE" ("ADDRESS_ID")
;

ALTER TABLE "EMPLOYEE" ADD CONSTRAINT "UNIQUE_IDENTIFIER4" PRIMARY KEY ("ID")
;

-- TABLE CUSTOMER

CREATE TABLE "CUSTOMER"
(
  "ID" CHARACTER VARYING(100) NOT NULL,
  "PASSWORD" CHARACTER VARYING(100) NOT NULL,
  "FIRST_NAME" CHARACTER VARYING(30) NOT NULL,
  "LAST_NAME" CHARACTER VARYING(50) NOT NULL,
  "PESEL" CHARACTER VARYING(15),
  "IS_ACTIVE" BOOLEAN,
  "LICENSE_NO" CHARACTER VARYING(50) NOT NULL,
  "REGISTEREDAT" DATE NOT NULL,
  "NOTES" TEXT,
  "ADDRESS_ID" INTEGER NOT NULL
)
WITH (
  AUTOVACUUM_ENABLED=TRUE)
;

CREATE INDEX "IX_REL_ADDRESS_2" ON "CUSTOMER" ("ADDRESS_ID")
;

ALTER TABLE "CUSTOMER" ADD CONSTRAINT "UNIQUE_IDENTIFIER5" PRIMARY KEY ("ID")
;

-- TABLE ADDRESS

CREATE TABLE "ADDRESS"
(
  "ID" SERIAL,
  "ADDRESS1" CHARACTER VARYING(150) NOT NULL,
  "ADDRESS2" CHARACTER VARYING(150),
  "POSTAL_CODE" CHARACTER VARYING(10) NOT NULL,
  "CITY" CHARACTER VARYING(50) NOT NULL
)
WITH (
  AUTOVACUUM_ENABLED=TRUE)
;

ALTER TABLE "ADDRESS" ADD CONSTRAINT "ID_ADDRESS" PRIMARY KEY ("ID")
;

-- TABLE ROLE

CREATE TABLE "ROLE"
(
  "ID" INTEGER NOT NULL,
  "NAME" CHARACTER VARYING(30) NOT NULL,
  "DESCRIPTION" TEXT
)
WITH (
  AUTOVACUUM_ENABLED=TRUE)
;

ALTER TABLE "ROLE" ADD CONSTRAINT "ID_ROLE" PRIMARY KEY ("ID")
;

-- TABLE EMPLOYEE_ROLE

CREATE TABLE "EMPLOYEE_ROLE"
(
  "ROLE_ID" INTEGER NOT NULL,
  "EMPLOYEE_ID" CHARACTER VARYING(100) NOT NULL
)
WITH (
  AUTOVACUUM_ENABLED=TRUE)
;

-- CREATE FOREIGN KEYS (RELATIONSHIPS) SECTION -------------------------------------------------

ALTER TABLE "PAYMENT"
  ADD CONSTRAINT "REL_PAYMENT_STATUS"
    FOREIGN KEY ("PAYMENT_STATUS_ID")
    REFERENCES "PAYMENT_STATUS" ("ID")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "CAR_STATUS"
  ADD CONSTRAINT "REL_CAR_STATUS"
    FOREIGN KEY ("CAR_ID")
    REFERENCES "CAR" ("ID")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "CAR_MODEL"
  ADD CONSTRAINT "REL_CAR_CLASS"
    FOREIGN KEY ("CAR_CLASS_ID")
    REFERENCES "CAR_CLASS" ("ID")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "CAR_CLASS"
  ADD CONSTRAINT "REL_DISCOUNT"
    FOREIGN KEY ("DISCOUNT_ID")
    REFERENCES "DISCOUNT" ("ID")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "CAR_MODEL"
  ADD CONSTRAINT "REL_CAR_BRAND"
    FOREIGN KEY ("CAR_BRAND_ID")
    REFERENCES "CAR_BRAND" ("ID")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "CAR_MODEL"
  ADD CONSTRAINT "REL_ENGINE_TYPE"
    FOREIGN KEY ("ENGINE_TYPE_ID")
    REFERENCES "ENGINE_TYPE" ("ID")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "RESERVATION_STATUS"
  ADD CONSTRAINT "REL_RESERVATION_STATUS"
    FOREIGN KEY ("RESERVATION_ID")
    REFERENCES "RESERVATION" ("ID")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "CAR"
  ADD CONSTRAINT "REL_CAR_RENTAL"
    FOREIGN KEY ("RENTAL_ID")
    REFERENCES "RENTAL" ("ID")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "RENTAL"
  ADD CONSTRAINT "REL_PAYMENT"
    FOREIGN KEY ("PAYMENT_ID")
    REFERENCES "PAYMENT" ("ID")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "RENTAL"
  ADD CONSTRAINT "REL_RENTAL_EMPLOYEE"
    FOREIGN KEY ("EMPLOYEE_ID")
    REFERENCES "EMPLOYEE" ("ID")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "RENTAL"
  ADD CONSTRAINT "REL_RENTAL_CUSTOMER"
    FOREIGN KEY ("CUSTOMER_ID")
    REFERENCES "CUSTOMER" ("ID")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "RESERVATION"
  ADD CONSTRAINT "REL_RESERV_CUSTOMER"
    FOREIGN KEY ("CUSTOMER_ID")
    REFERENCES "CUSTOMER" ("ID")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "CAR"
  ADD CONSTRAINT "REL_CAR_MODEL"
    FOREIGN KEY ("CAR_MODEL_ID")
    REFERENCES "CAR_MODEL" ("ID")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

ALTER TABLE "CAR_CLASS"
  ADD CONSTRAINT "REL_RESERVATION"
    FOREIGN KEY ("RESERVATION_ID")
    REFERENCES "RESERVATION" ("ID")
      ON DELETE NO ACTION
      ON UPDATE NO ACTION
;

